//
//  MessagesViewController.swift
//  WordArtMessage
//
//  Created by Joseph Adam Iannazzone on 3/8/23.
//

import UIKit
import SwiftUI
import Messages

@objc(MessagesViewController)

class MessagesViewController: MSMessagesAppViewController {
    
    let outputModel = FancyTextModel(isFullApp: false)
    let userSettings = UserSettings()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let detailViewController = UIHostingController(
            rootView: ContentView(outputModel: self.outputModel)
        )
        
        self.addChild(detailViewController)
        view.addSubview(detailViewController.view)
        detailViewController.view.frame = view.bounds
        detailViewController.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        detailViewController.didMove(toParent: self)
        
        outputModel.expand = {
            self.requestPresentationStyle(.expanded)
        }
        
        outputModel.insert = {
            self.activeConversation?.insertText(self.outputModel.finalOutput)
            self.dismiss()
        }
        
        outputModel.dismiss = {
            self.dismiss()
        }
        
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Sync state when extension becomes active
        outputModel.isExpanded = (presentationStyle == .expanded)
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
        dismiss()
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Don't update state here — causes flicker since didTransition will set final state
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Single source of truth for presentation state changes
        outputModel.isExpanded = (presentationStyle == .expanded)
    }

}
